// Generated by Selenium IDE
package edu.pitt.cs;

import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("https://cs1632.appspot.com/");
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.xpath("//a[contains(text(),\'Reset\')]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//a[contains(text(),\'Reset\')]"));
      String attribute = element.getAttribute("href");
      vars.put("resetLink", attribute);
    }
    assertEquals(vars.get("resetLink").toString(), "http://localhost:8080/reset");
  }
  @Test
  public void tEST2RESET() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.linkText("Reset")).click();
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(1)")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(2)")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST3CATALOG() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.xpath("//img[@alt=\'Old Deuteronomy\']")).click();
    {
      WebElement element = driver.findElement(By.xpath("//img[@alt=\'Old Deuteronomy\']"));
      String attribute = element.getAttribute("src");
      vars.put("imageName", attribute);
    }
    assertEquals(vars.get("imageName").toString(), "http://localhost:8080/images/cat2.jpg");
  }
  @Test
  public void tEST4LISTING() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.linkText("Catalog")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".list-group-item:nth-child(1)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".list-group-item:nth-child(2)"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".list-group-item:nth-child(3)"));
      assert(elements.size() > 0);
    }
    vars.put("thirdListing", driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).getText());
    assertEquals(vars.get("thirdListing").toString(), "ID 3. Mistoffelees");
  }
  @Test
  public void tEST5RENTACAT() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(3) .btn"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".form-group:nth-child(4) .btn"));
      assert(elements.size() > 0);
    }
    vars.put("rentBtn", driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).getText());
    vars.put("returnBtn", driver.findElement(By.cssSelector(".form-group:nth-child(4) .btn")).getText());
    assertEquals(vars.get("rentBtn").toString(), "Rent");
    assertEquals(vars.get("returnBtn").toString(), "Return");
  }
  @Test
  public void tEST6RENT() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("rentID")).click();
    driver.findElement(By.id("rentID")).sendKeys("1");
    driver.findElement(By.cssSelector(".form-group:nth-child(3) .btn")).click();
    vars.put("rentedOut", driver.findElement(By.cssSelector(".list-group-item:nth-child(1)")).getText());
    assertEquals(vars.get("rentedOut").toString(), "Rented out");
    vars.put("secondListing", driver.findElement(By.cssSelector(".list-group-item:nth-child(2)")).getText());
    vars.put("thirdListing", driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).getText());
    vars.put("Success", driver.findElement(By.id("rentResult")).getText());
    assertEquals(vars.get("secondListing").toString(), "ID 2. Old Deuteronomy");
    assertEquals(vars.get("thirdListing").toString(), "ID 3. Mistoffelees");
    assertEquals(vars.get("Success").toString(), "Success!");
  }
  @Test
  public void tEST7RETURN() {
    // driver.get("https://cs1632.appspot.com/");
    js.executeScript("document.cookie = \"2=true\"");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    driver.findElement(By.id("returnID")).click();
    driver.findElement(By.id("returnID")).sendKeys("2");
    driver.findElement(By.cssSelector(".form-group:nth-child(4) .btn")).click();
    vars.put("id1", driver.findElement(By.cssSelector(".list-group-item:nth-child(1)")).getText());
    vars.put("id2", driver.findElement(By.cssSelector(".list-group-item:nth-child(2)")).getText());
    vars.put("id3", driver.findElement(By.cssSelector(".list-group-item:nth-child(3)")).getText());
    vars.put("Success", driver.findElement(By.id("returnResult")).getText());
    assertEquals(vars.get("id1").toString(), "ID 1. Jennyanydots");
    assertEquals(vars.get("id2").toString(), "ID 2. Old Deuteronomy");
    assertEquals(vars.get("id3").toString(), "ID 3. Mistoffelees");
    assertEquals(vars.get("Success").toString(), "Success!");
    driver.findElement(By.linkText("Reset")).click();
  }
  @Test
  public void tEST8FEEDACAT() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".btn"));
      assert(elements.size() > 0);
    }
    vars.put("Feed", driver.findElement(By.cssSelector(".btn")).getText());
    assertEquals(vars.get("Feed").toString(), "Feed");
  }
  @Test
  public void tEST9FEED() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.linkText("Feed-A-Cat")).click();
    driver.findElement(By.id("catnips")).click();
    driver.findElement(By.id("catnips")).sendKeys("6");
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("nom", driver.findElement(By.id("feedResult")).getText());
    assertEquals(vars.get("nom").toString(), "Nom, nom, nom.");
  }
  @Test
  public void tEST10GREETACAT() {
    // driver.get("https://cs1632.appspot.com/");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.linkText("Greet-A-Cat")).click();
    vars.put("meow", driver.findElement(By.cssSelector("#greeting > h4")).getText());
    assertEquals(vars.get("meow").toString(), "Meow!Meow!Meow!");
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    driver.manage().window().setSize(new Dimension(1578, 1392));
    driver.findElement(By.cssSelector("#greeting > h4")).click();
    vars.put("meowFromJenny", driver.findElement(By.cssSelector("#greeting > h4")).getText());
    assertEquals(vars.get("meowFromJenny").toString(), "Meow! from Jennyanydots.");
  }
  // @Test
  // public void dEFECT1FUNFEEDACAT() {
  //   // driver.get("https://cs1632.appspot.com/");
  //   driver.manage().window().setSize(new Dimension(1578, 1392));
  //   driver.findElement(By.linkText("Feed-A-Cat")).click(); 
  //   driver.findElement(By.id("catnips")).click();
  //   driver.findElement(By.id("catnips")).sendKeys("0");
  //   driver.findElement(By.cssSelector(".btn")).click();
  //   assertThat(driver.findElement(By.id("feedResult")).getText(), is("Cat fight!"));
  // }
  // @Test
  // public void dEFECT2FUNGREETACAT() {
  //   // driver.get("https://cs1632.appspot.com/");
  //   driver.manage().window().setSize(new Dimension(1578, 1392));
  //   js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=false\";document.cookie = \"3=false\";");
  //   driver.findElement(By.linkText("Greet-A-Cat")).click();
  //   assertThat(driver.findElement(By.xpath("//div[@id=\'greeting\']/h4")).getText(), is("Meow!Meow!"));
  // }
  // @Test
  // public void dEFECT3FUNGREETACAT() { 
  //   // driver.get("https://cs1632.appspot.com/");
  //   driver.manage().window().setSize(new Dimension(1578, 1392));
  //   js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=false\";document.cookie = \"3=false\";"); 
  //   driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
  //   assertThat(driver.findElement(By.cssSelector("#greeting > h4")).getText(), is("Jennyanydots is not here."));
  // }
}
